twig:
  default_path: "%kernel.project_dir%/templates"
  form_themes: ["form/fields.html.twig"]
  globals:
    profile: "%profile%"
when@test:
  twig:
    strict_variables: true
    exception_on_invalid_index: true
